config/routes.rb
Rails.application.routes.draw do

  resources :color_palette_widgets do
    collection do
      post 'bindUser', 'unbindUser', 'handleColor'
      get 'bindUser', 'unbindUser', 'handleColor'
    end
  end

  resources :associations do
    collection do
      post 'bindUser', 'unbindUser', 'handleText'
      get 'bindUser', 'unbindUser', 'handleText'
    end
  end

  resources :color_bar_library_widgets do
    collection do
      post 'handleColor', 'bindUser', 'unbindUser', 'checkUser', 'addColor', 'retrieveColors'
      get 'handleColor', 'bindUser', 'unbindUser', 'checkUser', 'addColor', 'retrieveColors'
    end
  end

  resources :color_bar_widgets do
    collection do
      post 'handleColor', 'bindUser', 'unbindUser'
      get 'handleColor', 'bindUser', 'unbindUser'
    end
  end

  resources :gradient_widgets do
    collection do
      post 'handleColor', 'unbindUser', 'bindUser'
      get 'handleColor', 'unbindUser', 'bindUser'
    end
  end

  resources :color_scheme_widgets

  resources :user_widgets do
    collection do
      get 'getWidgets', 'toggleHidden'
      post 'getWidgets'
    end
  end

  resources :users do
    collection do
      post 'syncData'
      get 'syncData'
    end
  end

  resources :widgets do
    collection do
      post 'handleColor'
      get 'handleColor'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_widget.rb
class UserWidget < ApplicationRecord
  belongs_to :widgetable, polymorphic: true
  belongs_to :user
end

app/controllers/user_widgets_controller.rb
class UserWidgetsController < ApplicationController
  before_action :set_user_widget, only: [:show, :edit, :update, :destroy]

  # GET /user_widgets
  # GET /user_widgets.json
  def index
    @user_widgets = UserWidget.all
  end

  # GET /user_widgets/1
  # GET /user_widgets/1.json
  def show
  end

  # GET /user_widgets/new
  def new
    @user_widget = UserWidget.new
  end

  # GET /user_widgets/1/edit
  def edit
  end

  # POST /user_widgets
  # POST /user_widgets.json
  def create
    @user_widget = UserWidget.new(user_widget_params)

    respond_to do |format|
      if @user_widget.save
        format.html { redirect_to @user_widget, notice: 'User widget was successfully created.' }
        format.json { render :show, status: :created, location: @user_widget }
      else
        format.html { render :new }
        format.json { render json: @user_widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_widgets/1
  # PATCH/PUT /user_widgets/1.json
  def update
    respond_to do |format|
      if @user_widget.update(user_widget_params)
        format.html { redirect_to @user_widget, notice: 'User widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_widget }
      else
        format.html { render :edit }
        format.json { render json: @user_widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_widgets/1
  # DELETE /user_widgets/1.json
  def destroy
    @user_widget.destroy
    respond_to do |format|
      format.html { redirect_to user_widgets_url, notice: 'User widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getWidgets
    @userId = params[:userId]
    @widgets = UserWidget.where(:user_id => @userId).find_each
    render json: { results: @widgets.map{ |e| { type: e.widgetable_type, hidden: e.hidden }}}
  end

  def toggleHidden
    $stdout.puts "toggling hide"
    @userId = params[:userId].to_i, @type = params[:type]
    if @userId != nil
      @userEntry = UserWidget.find_by(:widgetable_type => @type, :user_id => @userId)
      if @userEntry != nil
        @userEntry.update(:hidden => !@userEntry[:hidden])
        render json: JSON("result" => 0)
      else
        render json: JSON("result" => -1)
      end
    else
      render json: JSON("result" => -1)
      return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_widget
      @user_widget = UserWidget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_widget_params
      params.require(:user_widget).permit(:user_id, :widgetable_type, :widgetable_id)
    end
end

app/helpers/user_widgets_helper.rb
module UserWidgetsHelper
end

app/views/user_widgets/_form.html.erb
<%= form_with(model: user_widget, local: true) do |form| %>
  <% if user_widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_widget.errors.count, "error") %> prohibited this user_widget from being saved:</h2>

      <ul>
      <% user_widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :widgetable_type %>
    <%= form.text_field :widgetable_type %>
  </div>

  <div class="field">
    <%= form.label :widgetable_id %>
    <%= form.number_field :widgetable_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_widgets/edit.html.erb
<h1>Editing User Widget</h1>

<%= render 'form', user_widget: @user_widget %>

<%= link_to 'Show', @user_widget %> |
<%= link_to 'Back', user_widgets_path %>

app/views/user_widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Widgets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Widgetable type</th>
      <th>Widgetable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_widgets.each do |user_widget| %>
      <tr>
        <td><%= user_widget.user_id %></td>
        <td><%= user_widget.widgetable_type %></td>
        <td><%= user_widget.widgetable_id %></td>
        <td><%= link_to 'Show', user_widget %></td>
        <td><%= link_to 'Edit', edit_user_widget_path(user_widget) %></td>
        <td><%= link_to 'Destroy', user_widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Widget', new_user_widget_path %>

app/views/user_widgets/new.html.erb
<h1>New User Widget</h1>

<%= render 'form', user_widget: @user_widget %>

<%= link_to 'Back', user_widgets_path %>

app/views/user_widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_widget.user_id %>
</p>

<p>
  <strong>Widgetable type:</strong>
  <%= @user_widget.widgetable_type %>
</p>

<p>
  <strong>Widgetable:</strong>
  <%= @user_widget.widgetable_id %>
</p>

<%= link_to 'Edit', edit_user_widget_path(@user_widget) %> |
<%= link_to 'Back', user_widgets_path %>