config/routes.rb
Rails.application.routes.draw do

  resources :color_palette_widgets do
    collection do
      post 'bindUser', 'unbindUser', 'handleColor'
      get 'bindUser', 'unbindUser', 'handleColor'
    end
  end

  resources :associations do
    collection do
      post 'bindUser', 'unbindUser', 'handleText'
      get 'bindUser', 'unbindUser', 'handleText'
    end
  end

  resources :color_bar_library_widgets do
    collection do
      post 'handleColor', 'bindUser', 'unbindUser', 'checkUser', 'addColor', 'retrieveColors'
      get 'handleColor', 'bindUser', 'unbindUser', 'checkUser', 'addColor', 'retrieveColors'
    end
  end

  resources :color_bar_widgets do
    collection do
      post 'handleColor', 'bindUser', 'unbindUser'
      get 'handleColor', 'bindUser', 'unbindUser'
    end
  end

  resources :gradient_widgets do
    collection do
      post 'handleColor', 'unbindUser', 'bindUser'
      get 'handleColor', 'unbindUser', 'bindUser'
    end
  end

  resources :color_scheme_widgets

  resources :user_widgets do
    collection do
      get 'getWidgets', 'toggleHidden'
      post 'getWidgets'
    end
  end

  resources :users do
    collection do
      post 'syncData'
      get 'syncData'
    end
  end

  resources :widgets do
    collection do
      post 'handleColor'
      get 'handleColor'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/color_bar_widget.rb
class ColorBarWidget < ApplicationRecord
  has_many :user_widgets, as: :widgetable
end

app/controllers/color_bar_widgets_controller.rb
class ColorBarWidgetsController < ApplicationController
  before_action :set_color_bar_widget, only: [:show, :edit, :update, :destroy]

  # GET /color_bar_widgets
  # GET /color_bar_widgets.json
  def index
    @color_bar_widgets = ColorBarWidget.all
  end

  # GET /color_bar_widgets/1
  # GET /color_bar_widgets/1.json
  def show
  end

  # GET /color_bar_widgets/new
  def new
    @color_bar_widget = ColorBarWidget.new
  end

  # GET /color_bar_widgets/1/edit
  def edit
  end

  # POST /color_bar_widgets
  # POST /color_bar_widgets.json
  def create
    @color_bar_widget = ColorBarWidget.new(color_bar_widget_params)

    respond_to do |format|
      if @color_bar_widget.save
        format.html { redirect_to @color_bar_widget, notice: 'Color bar widget was successfully created.' }
        format.json { render :show, status: :created, location: @color_bar_widget }
      else
        format.html { render :new }
        format.json { render json: @color_bar_widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /color_bar_widgets/1
  # PATCH/PUT /color_bar_widgets/1.json
  def update
    respond_to do |format|
      if @color_bar_widget.update(color_bar_widget_params)
        format.html { redirect_to @color_bar_widget, notice: 'Color bar widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @color_bar_widget }
      else
        format.html { render :edit }
        format.json { render json: @color_bar_widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /color_bar_widgets/1
  # DELETE /color_bar_widgets/1.json
  def destroy
    @color_bar_widget.destroy
    respond_to do |format|
      format.html { redirect_to color_bar_widgets_url, notice: 'Color bar widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bindUser
    @req = request.body.read
    unless @req.blank?
      @userId = params[:userId]
      @wdgLast = ColorBarWidget.last()
      unless @wdgLast.nil?
        @userWidget = UserWidget.find_by(:widgetable_type => "ColorBarWidget", :user_id => @userId.to_i)
        unless @userWidget.nil?
          puts "this user has widget binded"
          render json: JSON("result" => 1)
          return
        else
          @wdgLast = ColorBarWidget.create()
        end
      else
        @wdgLast = ColorBarWidget.create()
      end
      @wdgType = "ColorBarWidget"
      puts "parameters: ", @userId, @wdgLast[:id], @wdgType
      @newUserWidget = UserWidget.create(:user_id => @userId, :widgetable_type => @wdgType, :widgetable_id => @wdgLast[:id])
      @curUser = User.find(@userId)
      @curUser.user_widgets << @newUserWidget
      @wdgLast.user_widgets << @newUserWidget
      puts ''
      puts "Checking table"
      puts UserWidget.all.each { |e| puts e.inspect }
      @user_entries = User.includes(:user_widgets).where(user_widgets: {widgetable_type: 'ColorBarWidget'})
      @user_entries.each do |u|
        puts u[:user_id]
      end
      render json: JSON("result" => '1')
      return
    else
      $stoud.puts "cant bind, no user id"
      render json: JSON("result" => '0')
    end
  end

  def unbindUser
    @req = request.body.read
    unless @req.blank?
      @userId = params[:userId]
      @wdgLast = ColorBarWidget.last()
      unless @wdgLast.nil?
        @userWidget = UserWidget.find_by(:widgetable_type => "ColorBarWidget", :user_id => @userId.to_i)
        unless @userWidget.nil?
          @userWidget.destroy
          puts "widget has been unbinded"
          render json: JSON("result" => 1)
          return
        else
          render json: JSON("result" => 0)
          return
        end
      else
        render json: JSON("result" => 0)
        return
      end
    else
      $stoud.puts "cant destroy, no user id"
      render json: JSON("result" => '0')
    end
  end

  def handleColor
    $stdout.puts "Handling COLOR BAR WIDGET color"
    @userId, @color = params[:userId].to_i, params[:color]
    puts @userId, @color
    if @userId != nil
      @userEntry = UserWidget.find_by(:widgetable_type => "ColorBarWidget", :user_id => @userId)
      if @userEntry.nil?
        puts "cant find entry for this user"
        render json: JSON("result" => "0")
        return
      else
        if (@color != nil)
          puts "updating color in database"
          ColorBarWidget.update(@userEntry[:widgetable_id], :color => @color)
          render json: JSON("result" => "0")
          return
        else
          puts "retrieving colors from database"
          @cbWdg = ColorBarWidget.find(@userEntry[:widgetable_id])
          @color = @cbWdg[:color]
          render json: JSON("result" => "1", "color" => @color)
          return
        end
      end
    else
      puts "userId is null"
      render json: JSON("result" => "0")
      return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color_bar_widget
      @color_bar_widget = ColorBarWidget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_bar_widget_params
      params.require(:color_bar_widget).permit(:color)
    end
end

app/helpers/color_bar_widgets_helper.rb
module ColorBarWidgetsHelper
end

app/views/color_bar_widgets/_form.html.erb
<%= form_with(model: color_bar_widget, local: true) do |form| %>
  <% if color_bar_widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(color_bar_widget.errors.count, "error") %> prohibited this color_bar_widget from being saved:</h2>

      <ul>
      <% color_bar_widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/color_bar_widgets/edit.html.erb
<h1>Editing Color Bar Widget</h1>

<%= render 'form', color_bar_widget: @color_bar_widget %>

<%= link_to 'Show', @color_bar_widget %> |
<%= link_to 'Back', color_bar_widgets_path %>

app/views/color_bar_widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Color Bar Widgets</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @color_bar_widgets.each do |color_bar_widget| %>
      <tr>
        <td><%= color_bar_widget.color %></td>
        <td><%= link_to 'Show', color_bar_widget %></td>
        <td><%= link_to 'Edit', edit_color_bar_widget_path(color_bar_widget) %></td>
        <td><%= link_to 'Destroy', color_bar_widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Color Bar Widget', new_color_bar_widget_path %>

app/views/color_bar_widgets/new.html.erb
<h1>New Color Bar Widget</h1>

<%= render 'form', color_bar_widget: @color_bar_widget %>

<%= link_to 'Back', color_bar_widgets_path %>

app/views/color_bar_widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @color_bar_widget.color %>
</p>

<%= link_to 'Edit', edit_color_bar_widget_path(@color_bar_widget) %> |
<%= link_to 'Back', color_bar_widgets_path %>