config/routes.rb
Rails.application.routes.draw do

  resources :color_palette_widgets do
    collection do
      post 'bindUser', 'unbindUser', 'handleColor'
      get 'bindUser', 'unbindUser', 'handleColor'
    end
  end

  resources :associations do
    collection do
      post 'bindUser', 'unbindUser', 'handleText'
      get 'bindUser', 'unbindUser', 'handleText'
    end
  end

  resources :color_bar_library_widgets do
    collection do
      post 'handleColor', 'bindUser', 'unbindUser', 'checkUser', 'addColor', 'retrieveColors'
      get 'handleColor', 'bindUser', 'unbindUser', 'checkUser', 'addColor', 'retrieveColors'
    end
  end

  resources :color_bar_widgets do
    collection do
      post 'handleColor', 'bindUser', 'unbindUser'
      get 'handleColor', 'bindUser', 'unbindUser'
    end
  end

  resources :gradient_widgets do
    collection do
      post 'handleColor', 'unbindUser', 'bindUser'
      get 'handleColor', 'unbindUser', 'bindUser'
    end
  end

  resources :color_scheme_widgets

  resources :user_widgets do
    collection do
      get 'getWidgets', 'toggleHidden'
      post 'getWidgets'
    end
  end

  resources :users do
    collection do
      post 'syncData'
      get 'syncData'
    end
  end

  resources :widgets do
    collection do
      post 'handleColor'
      get 'handleColor'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/widgets_controller.rb
require "json"

class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def handleColor
    string = request.body.read
    unless string.to_s.strip.empty?
      $stdout.puts "string not empty, " + string
      file = File.open("color.txt", "w")
      file.write(string)
      file.close()
    else
      if File.exists?("color.txt")
        file = File.open("color.txt", 'r')
        ln = file.readline() { |line| return line}
        render html: ln
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:title)
    end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<%= form_with(model: widget, local: true) do |form| %>
  <% if widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Widgets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.title %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @widget.title %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>