config/routes.rb
Rails.application.routes.draw do

  resources :color_palette_widgets do
    collection do
      post 'bindUser', 'unbindUser', 'handleColor'
      get 'bindUser', 'unbindUser', 'handleColor'
    end
  end

  resources :associations do
    collection do
      post 'bindUser', 'unbindUser', 'handleText'
      get 'bindUser', 'unbindUser', 'handleText'
    end
  end

  resources :color_bar_library_widgets do
    collection do
      post 'handleColor', 'bindUser', 'unbindUser', 'checkUser', 'addColor', 'retrieveColors'
      get 'handleColor', 'bindUser', 'unbindUser', 'checkUser', 'addColor', 'retrieveColors'
    end
  end

  resources :color_bar_widgets do
    collection do
      post 'handleColor', 'bindUser', 'unbindUser'
      get 'handleColor', 'bindUser', 'unbindUser'
    end
  end

  resources :gradient_widgets do
    collection do
      post 'handleColor', 'unbindUser', 'bindUser'
      get 'handleColor', 'unbindUser', 'bindUser'
    end
  end

  resources :color_scheme_widgets

  resources :user_widgets do
    collection do
      get 'getWidgets', 'toggleHidden'
      post 'getWidgets'
    end
  end

  resources :users do
    collection do
      post 'syncData'
      get 'syncData'
    end
  end

  resources :widgets do
    collection do
      post 'handleColor'
      get 'handleColor'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gradient_widget.rb
class GradientWidget < ApplicationRecord
  has_many :user_widgets, as: :widgetable
end

app/controllers/gradient_widgets_controller.rb
require "json"

class GradientWidgetsController < ApplicationController
  before_action :set_gradient_widget, only: [:show, :edit, :update, :destroy]

  # GET /gradient_widgets
  # GET /gradient_widgets.json
  def index
    @gradient_widgets = GradientWidget.all
  end

  # GET /gradient_widgets/1
  # GET /gradient_widgets/1.json
  def show
  end

  # GET /gradient_widgets/new
  def new
    @gradient_widget = GradientWidget.new
  end

  # GET /gradient_widgets/1/edit
  def edit
  end

  # POST /gradient_widgets
  # POST /gradient_widgets.json
  def create
    @gradient_widget = GradientWidget.new(gradient_widget_params)

    respond_to do |format|
      if @gradient_widget.save
        format.html { redirect_to @gradient_widget, notice: 'Gradient widget was successfully created.' }
        format.json { render :show, status: :created, location: @gradient_widget }
      else
        format.html { render :new }
        format.json { render json: @gradient_widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gradient_widgets/1
  # PATCH/PUT /gradient_widgets/1.json
  def update
    respond_to do |format|
      if @gradient_widget.update(gradient_widget_params)
        format.html { redirect_to @gradient_widget, notice: 'Gradient widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @gradient_widget }
      else
        format.html { render :edit }
        format.json { render json: @gradient_widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gradient_widgets/1
  # DELETE /gradient_widgets/1.json
  def destroy
    @gradient_widget.destroy
    respond_to do |format|
      format.html { redirect_to gradient_widgets_url, notice: 'Gradient widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bindUser
    @req = request.body.read
    unless @req.blank?
      @userId = params[:userId]
      @wdgLast = GradientWidget.last()
      unless @wdgLast.nil?
        @userWidget = UserWidget.find_by(:widgetable_type => "GradientWidget", :user_id => @userId.to_i)
        unless @userWidget.nil?
          puts "this user has widget binded"
          render json: JSON("result" => 1)
          return
        else
          @wdgLast = GradientWidget.create()
        end
      else
        @wdgLast = GradientWidget.create()
      end
      @wdgType = "GradientWidget"
      puts "parameters: ", @userId, @wdgLast[:id], @wdgType
      @newUserWidget = UserWidget.create(:user_id => @userId, :widgetable_type => @wdgType, :widgetable_id => @wdgLast[:id])
      @curUser = User.find(@userId)
      @curUser.user_widgets << @newUserWidget
      @wdgLast.user_widgets << @newUserWidget
      puts ''
      puts "Checking table"
      puts UserWidget.all.each { |e| puts e.inspect }
      @user_entries = User.includes(:user_widgets).where(user_widgets: {widgetable_type: 'GradientWidget'})
      @user_entries.each do |u|
        puts u[:user_id]
      end
      render json: JSON("result" => '1')
      return
    else
      $stoud.puts "cant bind, no user id"
      render json: JSON("result" => '0')
    end
  end

  def unbindUser
    @req = request.body.read
    unless @req.blank?
      @userId = params[:userId]
      @wdgLast = GradientWidget.last()
      unless @wdgLast.nil?
        @userWidget = UserWidget.find_by(:widgetable_type => "GradientWidget", :user_id => @userId.to_i)
        unless @userWidget.nil?
          @userWidget.destroy
          puts "widget has been unbinded"
          render json: JSON("result" => 1)
          return
        else
          render json: JSON("result" => 0)
          return
        end
      else
        render json: JSON("result" => 0)
        return
      end
    else
      $stoud.puts "cant destroy, no user id"
      render json: JSON("result" => '0')
    end
  end

  def handleColor
    $stdout.puts "Handling gradient colors"
    @userId, @startColor, @endColor = params[:userId].to_i, params[:startColor], params[:endColor]
    puts @userId, @startColor, @endColor
    if @userId != nil
      @userEntry = UserWidget.find_by(:widgetable_type => "GradientWidget", :user_id => @userId)
      if @userEntry.nil?
        puts "cant find entry for this user"
        render json: JSON("result" => "0")
        return
      else
        if (@startColor != nil) && (@endColor != nil)
          puts "updating color in database"
          GradientWidget.update(@userEntry[:widgetable_id], :start_color => @startColor, :end_color => @endColor)
          render json: JSON("result" => "0")
          return
        else
          puts "retrieving colors from database"
          @grdWdg = GradientWidget.find(@userEntry[:widgetable_id])
          @startColor, @endColor = @grdWdg[:start_color], @grdWdg[:end_color]
          render json: JSON("result" => "1", "startColor" => @startColor, "endColor" => @endColor)
          return
        end
      end
    else
      "no user id, cant do anything"
      render json: JSON("result" => "0")
      return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gradient_widget
      @gradient_widget = GradientWidget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gradient_widget_params
      params.require(:gradient_widget).permit(:start_color, :end_color)
    end
end

app/helpers/gradient_widgets_helper.rb
module GradientWidgetsHelper
end

app/views/gradient_widgets/_form.html.erb
<%= form_with(model: gradient_widget, local: true) do |form| %>
  <% if gradient_widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gradient_widget.errors.count, "error") %> prohibited this gradient_widget from being saved:</h2>

      <ul>
      <% gradient_widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_color %>
    <%= form.text_field :start_color %>
  </div>

  <div class="field">
    <%= form.label :end_color %>
    <%= form.text_field :end_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gradient_widgets/edit.html.erb
<h1>Editing Gradient Widget</h1>

<%= render 'form', gradient_widget: @gradient_widget %>

<%= link_to 'Show', @gradient_widget %> |
<%= link_to 'Back', gradient_widgets_path %>

app/views/gradient_widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gradient Widgets</h1>

<table>
  <thead>
    <tr>
      <th>Start color</th>
      <th>End color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gradient_widgets.each do |gradient_widget| %>
      <tr>
        <td><%= gradient_widget.start_color %></td>
        <td><%= gradient_widget.end_color %></td>
        <td><%= link_to 'Show', gradient_widget %></td>
        <td><%= link_to 'Edit', edit_gradient_widget_path(gradient_widget) %></td>
        <td><%= link_to 'Destroy', gradient_widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gradient Widget', new_gradient_widget_path %>

app/views/gradient_widgets/new.html.erb
<h1>New Gradient Widget</h1>

<%= render 'form', gradient_widget: @gradient_widget %>

<%= link_to 'Back', gradient_widgets_path %>

app/views/gradient_widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start color:</strong>
  <%= @gradient_widget.start_color %>
</p>

<p>
  <strong>End color:</strong>
  <%= @gradient_widget.end_color %>
</p>

<%= link_to 'Edit', edit_gradient_widget_path(@gradient_widget) %> |
<%= link_to 'Back', gradient_widgets_path %>